stages:
  - test
  - build
  - deploy

# Run flake8 to check for code quality
lint-test-job:
  image: python:3-bullseye
  stage: test
  script:
    - pip install flake8
    - flake8 --max-line-length 200 accountsapi
    - flake8 --max-line-length 200 tagsapi


api-unit-test-job:
  image: python:3-bullseye
  stage: test
  needs:
    - lint-test-job
  variables:
    SIGNING_KEY: aki
  script:
    - cd accountsapi
    - pip install -r requirements.txt
    - python -m pytest

# Build the React/JavaScript front-end
build-front-end-job:
  stage: build
  image: node:lts-bullseye
  needs:
    - lint-test-job
    - api-unit-test-job
  variables:
    PUBLIC_URL: https://caffeine-anonymous.gitlab.io/coffee-tavern/
    REACT_APP_SAMPLE_SERVICE_API_HOST: https://coffee-tavernn.onrender.com
    REACT_APP_SAMPLE_SERVICE_API_HOST2: https://coffee-tavern.onrender.com
  script:
    - cd ghi
    - cd coffee-tavern
    - npm install
    - npm run build
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - ghi/coffee-tavern/build

build-front-end-job2:
  stage: build
  image: node:lts-bullseye
  needs:
    - lint-test-job
    - api-unit-test-job
  variables:
    PUBLIC_URL: https://caffeine-anonymous.gitlab.io/coffee-tavern/
    REACT_APP_SAMPLE_SERVICE_API_HOST: https://coffee-tavernn.onrender.com
    REACT_APP_SAMPLE_SERVICE_API_HOST2: https://coffee-tavern.onrender.com
  script:
    - cd ghi
    - cd coffee-tavern
    - npm install
    - npm run build
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - ghi/coffee-tavern/tags/build

# Deploy the React/JavaScript front-end to GitLab pages
pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  dependencies:
    - build-front-end-job
    - build-front-end-job2
  needs:
    - build-front-end-job
    - build-fron-end-job2
  script:
    - mv ghi/coffee-tavern/build public
    - mv ghi/coffee-tavern/tags/build public
  artifacts:
    paths:
      - public
