stages:
  - test
  - build
  - deploy

# Run flake8 to check for code quality
lint-test-job:
  image: python:3-bullseye
  stage: test
  script:
    - pip install flake8
    - flake8 --max-line-length 200 accountsapi
    - flake8 --max-line-length 200 tagsapi


# api-unit-test-job:
#   image: python:3-bullseye
#   stage: test
#   needs:
#     - lint-test-job
#   script:
#     - cd coffee-tavern
#     - 
#     - pip install -r requirements.txt
#     - cd accountsapi
#     - 
#     - python -m pytest

# Build the React/JavaScript front-end
build-front-end-job:
  stage: build
  image: node:lts-bullseye
  needs:
    - lint-test-job
  variables:
    PUBLIC_URL: https://gitlab.com/caffeine-anonymous/coffee-tavern
    REACT_APP_SAMPLE_SERVICE_API_HOST: https://coffee-tavern.onrender.com
  script:
    - cd ghi
    - cd coffee-tavern
    - npm install
    - npm run build
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - ghi/coffee-tavern/

# Deploy the React/JavaScript front-end to GitLab pages
pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  dependencies:
    - build-front-end-job
  needs:
    - build-front-end-job
  script:
    - mv ghi/coffee-tavern public
  artifacts:
    paths:
      - public
