volumes:
  coffee_tavern-data:
    external: true
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: postgresql://coffee:tavern@db/coffee_tavern
      WAIT_HOSTS: db:5432
      PORT: 8000
      SIGNING_KEY: aki
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
  react:
    build: ./coffee-tavern
    container_name: react1
    ports:
      - '3000:3000'
    volumes:
      - ./coffee-tavern:/app
    stdin_open: true
    tty: true
  db:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_PASSWORD: tavern
      POSTGRES_USER: coffee
      POSTGRES_DB: coffee_tavern
    ports:
      - "15432:5432"
    volumes:
      - coffee_tavern-data:/var/lib/postgresql/data
